package vault

import (
	"os"
	"path/filepath"
	"testing"
)

// Fixture files live in testdata and are regenerated by
// TestGenerateFixtures when the -regen flag is set. The checked-in copies
// are what the other tests read, so a change in gokeepasslib's writer shows
// up as a decode failure against a file this code did not just produce.
const (
	fixturePassword = "correct horse battery staple"
	fixtureKeyData  = "vaulty test key file, not a secret"
)

type fixture struct {
	name    string
	file    string
	creds   Credentials
	version string
}

// fixtures enumerates the four combinations the vault must open.
func fixtures(t *testing.T) []fixture {
	t.Helper()
	keyPath := filepath.Join("testdata", "key.keyx")
	return []fixture{
		{
			name:    "kdbx31_password",
			file:    filepath.Join("testdata", "kdbx31-password.kdbx"),
			creds:   Credentials{Password: fixturePassword},
			version: "3.1",
		},
		{
			name:    "kdbx31_password_keyfile",
			file:    filepath.Join("testdata", "kdbx31-password-keyfile.kdbx"),
			creds:   Credentials{Password: fixturePassword, KeyFile: keyPath},
			version: "3.1",
		},
		{
			name:    "kdbx40_password",
			file:    filepath.Join("testdata", "kdbx40-password.kdbx"),
			creds:   Credentials{Password: fixturePassword},
			version: "4.0",
		},
		{
			name:    "kdbx40_password_keyfile",
			file:    filepath.Join("testdata", "kdbx40-password-keyfile.kdbx"),
			creds:   Credentials{Password: fixturePassword, KeyFile: keyPath},
			version: "4.0",
		},
	}
}

// copyFixture puts a fixture in a temp dir so a test that saves cannot
// modify the checked-in file.
func copyFixture(t *testing.T, src string) string {
	t.Helper()
	data, err := os.ReadFile(src)
	if err != nil {
		t.Fatalf("read fixture %s: %v", src, err)
	}
	dst := filepath.Join(t.TempDir(), filepath.Base(src))
	if err := os.WriteFile(dst, data, 0o600); err != nil {
		t.Fatalf("write fixture copy: %v", err)
	}
	return dst
}

// keyFileCopy returns a path to the fixture key file usable from any temp dir.
func keyFileCopy(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "key.keyx")
}
